### ISSUE TITLE
任务提交失败

### ISSUE THREAD

**Issue by wuyueandrew** [TuGraph-family/tugraph-analytics#130]
猜测是k8s客户端不兼容k3s

k3s环境如下：
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.7+k3s1", GitCommit:"ec61c6673a1198b2451356d22044a0b2a0edf028", GitTreeState:"clean", BuildDate:"2022-06-13T18:57:16Z", GoVersion:"go1.17.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.7+k3s1", GitCommit:"ec61c6673a1198b2451356d22044a0b2a0edf028", GitTreeState:"clean", BuildDate:"2022-06-13T18:57:16Z", GoVersion:"go1.17.5", Compiler:"gc", Platform:"linux/amd64"}

**Describe the bug**
2023-08-18 10:18:27,463 INFO  http-nio-8080-exec-9 core.service.file.RemoteFileStorage:73   - Start upload file, url=http://graph-dataset.https://oss-cn-hangzhou.aliyuncs.com/geaflow/packages/1692348092757605146/release-4.zip
2023-08-18 10:18:27,635 INFO  http-nio-8080-exec-9 core.service.file.RemoteFileStorage:75   - Upload success, url=http://graph-dataset.https://oss-cn-hangzhou.aliyuncs.com/geaflow/packages/1692348092757605146/release-4.zip
2023-08-18 10:20:13,183 INFO  http-nio-8080-exec-1 core.service.file.RemoteFileStorage:73   - Start upload file, url=http://graph-dataset.https://oss-cn-hangzhou.aliyuncs.com/geaflow/packages/1692348092757605146/release-4.zip
2023-08-18 10:20:13,349 INFO  http-nio-8080-exec-1 core.service.file.RemoteFileStorage:75   - Upload success, url=http://graph-dataset.https://oss-cn-hangzhou.aliyuncs.com/geaflow/packages/1692348092757605146/release-4.zip
2023-08-18 10:20:13,350 WARN  http-nio-8080-exec-1 common.dal.dao.ReleaseDao:179  - SqlSession [org.apache.ibatis.session.defaults.DefaultSqlSession@25a4083e] Transaction not enabled
2023-08-18 10:20:13,419 INFO  http-nio-8080-exec-2 biz.shared.impl.TaskManagerImpl:148  - submit task successfully, waiting for scheduling. id: 1692348104001846335
2023-08-18 10:20:20,001 INFO  scheduling-1 core.service.task.GeaflowTaskSubmitter:61   - task submitter start, task size: 1
2023-08-18 10:20:20,015 INFO  pool-3-thread-5 core.service.task.GeaflowTaskSubmitter:75   - task 1692348104001846335 submit start, curr status: WAITING
2023-08-18 10:20:20,023 ERROR pool-3-thread-5 common.util.exception.GeaflowLogException:24   - Start task 1692348104001846335 failed
com.antgroup.geaflow.console.common.util.exception.GeaflowException: Create instance of K8sJobClient failed
        at com.antgroup.geaflow.console.common.util.proxy.ProxyUtil.newInstance(ProxyUtil.java:54) ~[geaflow-console-common-util-0.3-SNAPSHOT.jar!/:?]
        at com.antgroup.geaflow.console.core.service.version.VersionClassLoader.newInstance(VersionClassLoader.java:47) ~[geaflow-console-core-service-0.3-SNAPSHOT.jar!/:?]
        at com.antgroup.geaflow.console.core.service.runtime.K8sRuntime.doStart(K8sRuntime.java:85) ~[geaflow-console-core-service-0.3-SNAPSHOT.jar!/:?]
        at com.antgroup.geaflow.console.core.service.runtime.K8sRuntime.start(K8sRuntime.java:55) ~[geaflow-console-core-service-0.3-SNAPSHOT.jar!/:?]
        at com.antgroup.geaflow.console.core.service.task.GeaflowTaskOperator.start(GeaflowTaskOperator.java:100) ~[geaflow-console-core-service-0.3-SNAPSHOT.jar!/:?]
        at com.antgroup.geaflow.console.core.service.task.GeaflowTaskSubmitter.lambda$submit$0(GeaflowTaskSubmitter.java:83) ~[geaflow-console-core-service-0.3-SNAPSHOT.jar!/:?]
        at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1640) ~[?:1.8.0_382]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_382]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_382]
        at java.lang.Thread.run(Thread.java:750) ~[?:1.8.0_382]
Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_382]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_382]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_382]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_382]
        at com.antgroup.geaflow.console.common.util.proxy.ProxyUtil.lambda$newInstance$0(ProxyUtil.java:48) ~[geaflow-console-common-util-0.3-SNAPSHOT.jar!/:?]
        at com.antgroup.geaflow.console.common.util.LoaderSwitchUtil.call(LoaderSwitchUtil.java:38) ~[geaflow-console-common-util-0.3-SNAPSHOT.jar!/:?]
        at com.antgroup.geaflow.console.common.util.proxy.ProxyUtil.newInstance(ProxyUtil.java:37) ~[geaflow-console-common-util-0.3-SNAPSHOT.jar!/:?]
        ... 9 more
Caused by: io.fabric8.kubernetes.client.KubernetesClientException: An error has occurred.
        at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:64) ~[?:?]
        at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:53) ~[?:?]
        at io.fabric8.kubernetes.client.utils.HttpClientUtils.createHttpClient(HttpClientUtils.java:228) ~[?:?]
        at io.fabric8.kubernetes.client.utils.HttpClientUtils.createHttpClient(HttpClientUtils.java:66) ~[?:?]
        at com.antgroup.geaflow.cluster.k8s.clustermanager.KubernetesClientFactory.create(KubernetesClientFactory.java:70) ~[?:?]
        at com.antgroup.geaflow.cluster.k8s.clustermanager.GeaflowKubeClient.<init>(GeaflowKubeClient.java:56) ~[?:?]
        at com.antgroup.geaflow.cluster.k8s.clustermanager.GeaflowKubeClient.<init>(GeaflowKubeClient.java:52) ~[?:?]
        at com.antgroup.geaflow.cluster.k8s.client.KubernetesJobClient.<init>(KubernetesJobClient.java:58) ~[?:?]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_382]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_382]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_382]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_382]
        at com.antgroup.geaflow.console.common.util.proxy.ProxyUtil.lambda$newInstance$0(ProxyUtil.java:48) ~[geaflow-console-common-util-0.3-SNAPSHOT.jar!/:?]
        at com.antgroup.geaflow.console.common.util.LoaderSwitchUtil.call(LoaderSwitchUtil.java:38) ~[geaflow-console-common-util-0.3-SNAPSHOT.jar!/:?]
        at com.antgroup.geaflow.console.common.util.proxy.ProxyUtil.newInstance(ProxyUtil.java:37) ~[geaflow-console-common-util-0.3-SNAPSHOT.jar!/:?]
        ... 9 more
Caused by: java.io.IOException: Invalid DER: object is not integer
        at io.fabric8.kubernetes.client.internal.PKCS1Util$Asn1Object.getInteger(PKCS1Util.java:125) ~[?:?]
        at io.fabric8.kubernetes.client.internal.PKCS1Util.next(PKCS1Util.java:55) ~[?:?]
        at io.fabric8.kubernetes.client.internal.PKCS1Util.decodePKCS1(PKCS1Util.java:46) ~[?:?]
        at io.fabric8.kubernetes.client.internal.CertUtils.handleOtherKeys(CertUtils.java:179) ~[?:?]
        at io.fabric8.kubernetes.client.internal.CertUtils.loadKey(CertUtils.java:139) ~[?:?]
        at io.fabric8.kubernetes.client.internal.CertUtils.createKeyStore(CertUtils.java:115) ~[?:?]
        at io.fabric8.kubernetes.client.internal.CertUtils.createKeyStore(CertUtils.java:251) ~[?:?]
        at io.fabric8.kubernetes.client.internal.SSLUtils.keyManagers(SSLUtils.java:128) ~[?:?]
        at io.fabric8.kubernetes.client.internal.SSLUtils.keyManagers(SSLUtils.java:122) ~[?:?]
        at io.fabric8.kubernetes.client.utils.HttpClientUtils.createHttpClient(HttpClientUtils.java:123) ~[?:?]
        at io.fabric8.kubernetes.client.utils.HttpClientUtils.createHttpClient(HttpClientUtils.java:66) ~[?:?]
        at com.antgroup.geaflow.cluster.k8s.clustermanager.KubernetesClientFactory.create(KubernetesClientFactory.java:70) ~[?:?]
        at com.antgroup.geaflow.cluster.k8s.clustermanager.GeaflowKubeClient.<init>(GeaflowKubeClient.java:56) ~[?:?]
        at com.antgroup.geaflow.cluster.k8s.clustermanager.GeaflowKubeClient.<init>(GeaflowKubeClient.java:52) ~[?:?]
        at com.antgroup.geaflow.cluster.k8s.client.KubernetesJobClient.<init>(KubernetesJobClient.java:58) ~[?:?]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_382]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_382]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_382]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_382]
        at com.antgroup.geaflow.console.common.util.proxy.ProxyUtil.lambda$newInstance$0(ProxyUtil.java:48) ~[geaflow-console-common-util-0.3-SNAPSHOT.jar!/:?]
        at com.antgroup.geaflow.console.common.util.LoaderSwitchUtil.call(LoaderSwitchUtil.java:38) ~[geaflow-console-common-util-0.3-SNAPSHOT.jar!/:?]
        at com.antgroup.geaflow.console.common.util.proxy.ProxyUtil.newInstance(ProxyUtil.java:37) ~[geaflow-console-common-util-0.3-SNAPSHOT.jar!/:?]
        ... 9 more
2023-08-18 10:20:20,023 ERROR pool-3-thread-5 core.service.task.GeaflowTaskOperator:109  - Submit task 1692348104001846335 failed
com.antgroup.geaflow.console.common.util.exception.GeaflowLogException: Start task 1692348104001846335 failed
        at com.antgroup.geaflow.console.core.service.runtime.K8sRuntime.doStart(K8sRuntime.java:96) ~[geaflow-console-core-service-0.3-SNAPSHOT.jar!/:?]
        at com.antgroup.geaflow.console.core.service.runtime.K8sRuntime.start(K8sRuntime.java:55) ~[geaflow-console-core-service-0.3-SNAPSHOT.jar!/:?]
        at com.antgroup.geaflow.console.core.service.task.GeaflowTaskOperator.start(GeaflowTaskOperator.java:100) ~[geaflow-console-core-service-0.3-SNAPSHOT.jar!/:?]
        at com.antgroup.geaflow.console.core.service.task.GeaflowTaskSubmitter.lambda$submit$0(GeaflowTaskSubmitter.java:83) ~[geaflow-console-core-service-0.3-SNAPSHOT.jar!/:?]
        at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1640) ~[?:1.8.0_382]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_382]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_382]
        at java.lang.Thread.run(Thread.java:750) ~[?:1.8.0_382]
Caused by: com.antgroup.geaflow.console.common.util.exception.GeaflowException: Create instance of K8sJobClient failed
        at com.antgroup.geaflow.console.common.util.proxy.ProxyUtil.newInstance(ProxyUtil.java:54) ~[geaflow-console-common-util-0.3-SNAPSHOT.jar!/:?]
        at com.antgroup.geaflow.console.core.service.version.VersionClassLoader.newInstance(VersionClassLoader.java:47) ~[geaflow-console-core-service-0.3-SNAPSHOT.jar!/:?]
        at com.antgroup.geaflow.console.core.service.runtime.K8sRuntime.doStart(K8sRuntime.java:85) ~[geaflow-console-core-service-0.3-SNAPSHOT.jar!/:?]
        ... 7 more
Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_382]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_382]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_382]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_382]
        at com.antgroup.geaflow.console.common.util.proxy.ProxyUtil.lambda$newInstance$0(ProxyUtil.java:48) ~[geaflow-console-common-util-0.3-SNAPSHOT.jar!/:?]
        at com.antgroup.geaflow.console.common.util.LoaderSwitchUtil.call(LoaderSwitchUtil.java:38) ~[geaflow-console-common-util-0.3-SNAPSHOT.jar!/:?]
        at com.antgroup.geaflow.console.common.util.proxy.ProxyUtil.newInstance(ProxyUtil.java:37) ~[geaflow-console-common-util-0.3-SNAPSHOT.jar!/:?]
        at com.antgroup.geaflow.console.core.service.version.VersionClassLoader.newInstance(VersionClassLoader.java:47) ~[geaflow-console-core-service-0.3-SNAPSHOT.jar!/:?]
        at com.antgroup.geaflow.console.core.service.runtime.K8sRuntime.doStart(K8sRuntime.java:85) ~[geaflow-console-core-service-0.3-SNAPSHOT.jar!/:?]
        ... 7 more
Caused by: io.fabric8.kubernetes.client.KubernetesClientException: An error has occurred.
        at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:64) ~[?:?]
        at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:53) ~[?:?]
        at io.fabric8.kubernetes.client.utils.HttpClientUtils.createHttpClient(HttpClientUtils.java:228) ~[?:?]
        at io.fabric8.kubernetes.client.utils.HttpClientUtils.createHttpClient(HttpClientUtils.java:66) ~[?:?]
        at com.antgroup.geaflow.cluster.k8s.clustermanager.KubernetesClientFactory.create(KubernetesClientFactory.java:70) ~[?:?]
        at com.antgroup.geaflow.cluster.k8s.clustermanager.GeaflowKubeClient.<init>(GeaflowKubeClient.java:56) ~[?:?]
        at com.antgroup.geaflow.cluster.k8s.clustermanager.GeaflowKubeClient.<init>(GeaflowKubeClient.java:52) ~[?:?]
        at com.antgroup.geaflow.cluster.k8s.client.KubernetesJobClient.<init>(KubernetesJobClient.java:58) ~[?:?]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_382]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_382]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_382]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_382]
        at com.antgroup.geaflow.console.common.util.proxy.ProxyUtil.lambda$newInstance$0(ProxyUtil.java:48) ~[geaflow-console-common-util-0.3-SNAPSHOT.jar!/:?]
        at com.antgroup.geaflow.console.common.util.LoaderSwitchUtil.call(LoaderSwitchUtil.java:38) ~[geaflow-console-common-util-0.3-SNAPSHOT.jar!/:?]
        at com.antgroup.geaflow.console.common.util.proxy.ProxyUtil.newInstance(ProxyUtil.java:37) ~[geaflow-console-common-util-0.3-SNAPSHOT.jar!/:?]
        at com.antgroup.geaflow.console.core.service.version.VersionClassLoader.newInstance(VersionClassLoader.java:47) ~[geaflow-console-core-service-0.3-SNAPSHOT.jar!/:?]
        at com.antgroup.geaflow.console.core.service.runtime.K8sRuntime.doStart(K8sRuntime.java:85) ~[geaflow-console-core-service-0.3-SNAPSHOT.jar!/:?]
        ... 7 more
Caused by: java.io.IOException: Invalid DER: object is not integer
        at io.fabric8.kubernetes.client.internal.PKCS1Util$Asn1Object.getInteger(PKCS1Util.java:125) ~[?:?]
        at io.fabric8.kubernetes.client.internal.PKCS1Util.next(PKCS1Util.java:55) ~[?:?]
        at io.fabric8.kubernetes.client.internal.PKCS1Util.decodePKCS1(PKCS1Util.java:46) ~[?:?]
        at io.fabric8.kubernetes.client.internal.CertUtils.handleOtherKeys(CertUtils.java:179) ~[?:?]
        at io.fabric8.kubernetes.client.internal.CertUtils.loadKey(CertUtils.java:139) ~[?:?]
        at io.fabric8.kubernetes.client.internal.CertUtils.createKeyStore(CertUtils.java:115) ~[?:?]
        at io.fabric8.kubernetes.client.internal.CertUtils.createKeyStore(CertUtils.java:251) ~[?:?]
        at io.fabric8.kubernetes.client.internal.SSLUtils.keyManagers(SSLUtils.java:128) ~[?:?]
        at io.fabric8.kubernetes.client.internal.SSLUtils.keyManagers(SSLUtils.java:122) ~[?:?]
        at io.fabric8.kubernetes.client.utils.HttpClientUtils.createHttpClient(HttpClientUtils.java:123) ~[?:?]
        at io.fabric8.kubernetes.client.utils.HttpClientUtils.createHttpClient(HttpClientUtils.java:66) ~[?:?]
        at com.antgroup.geaflow.cluster.k8s.clustermanager.KubernetesClientFactory.create(KubernetesClientFactory.java:70) ~[?:?]
        at com.antgroup.geaflow.cluster.k8s.clustermanager.GeaflowKubeClient.<init>(GeaflowKubeClient.java:56) ~[?:?]
        at com.antgroup.geaflow.cluster.k8s.clustermanager.GeaflowKubeClient.<init>(GeaflowKubeClient.java:52) ~[?:?]
        at com.antgroup.geaflow.cluster.k8s.client.KubernetesJobClient.<init>(KubernetesJobClient.java:58) ~[?:?]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_382]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_382]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_382]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_382]
        at com.antgroup.geaflow.console.common.util.proxy.ProxyUtil.lambda$newInstance$0(ProxyUtil.java:48) ~[geaflow-console-common-util-0.3-SNAPSHOT.jar!/:?]
        at com.antgroup.geaflow.console.common.util.LoaderSwitchUtil.call(LoaderSwitchUtil.java:38) ~[geaflow-console-common-util-0.3-SNAPSHOT.jar!/:?]
        at com.antgroup.geaflow.console.common.util.proxy.ProxyUtil.newInstance(ProxyUtil.java:37) ~[geaflow-console-common-util-0.3-SNAPSHOT.jar!/:?]
        at com.antgroup.geaflow.console.core.service.version.VersionClassLoader.newInstance(VersionClassLoader.java:47) ~[geaflow-console-core-service-0.3-SNAPSHOT.jar!/:?]
        at com.antgroup.geaflow.console.core.service.runtime.K8sRuntime.doStart(K8sRuntime.java:85) ~[geaflow-console-core-service-0.3-SNAPSHOT.jar!/:?]
        ... 7 more
2023-08-18 10:20:20,027 ERROR pool-3-thread-5 core.service.task.GeaflowTaskSubmitter:86   - task 1692348104001846335 submit error: Start task 1692348104001846335 failed
com.antgroup.geaflow.console.common.util.exception.GeaflowLogException: Start task 1692348104001846335 failed
        at com.antgroup.geaflow.console.core.service.runtime.K8sRuntime.doStart(K8sRuntime.java:96) ~[geaflow-console-core-service-0.3-SNAPSHOT.jar!/:?]
        at com.antgroup.geaflow.console.core.service.runtime.K8sRuntime.start(K8sRuntime.java:55) ~[geaflow-console-core-service-0.3-SNAPSHOT.jar!/:?]
        at com.antgroup.geaflow.console.core.service.task.GeaflowTaskOperator.start(GeaflowTaskOperator.java:100) ~[geaflow-console-core-service-0.3-SNAPSHOT.jar!/:?]
        at com.antgroup.geaflow.console.core.service.task.GeaflowTaskSubmitter.lambda$submit$0(GeaflowTaskSubmitter.java:83) ~[geaflow-console-core-service-0.3-SNAPSHOT.jar!/:?]
        at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1640) ~[?:1.8.0_382]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_382]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_382]
        at java.lang.Thread.run(Thread.java:750) ~[?:1.8.0_382]
Caused by: com.antgroup.geaflow.console.common.util.exception.GeaflowException: Create instance of K8sJobClient failed
        at com.antgroup.geaflow.console.common.util.proxy.ProxyUtil.newInstance(ProxyUtil.java:54) ~[geaflow-console-common-util-0.3-SNAPSHOT.jar!/:?]
        at com.antgroup.geaflow.console.core.service.version.VersionClassLoader.newInstance(VersionClassLoader.java:47) ~[geaflow-console-core-service-0.3-SNAPSHOT.jar!/:?]
        at com.antgroup.geaflow.console.core.service.runtime.K8sRuntime.doStart(K8sRuntime.java:85) ~[geaflow-console-core-service-0.3-SNAPSHOT.jar!/:?]
        ... 7 more
Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_382]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_382]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_382]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_382]
        at com.antgroup.geaflow.console.common.util.proxy.ProxyUtil.lambda$newInstance$0(ProxyUtil.java:48) ~[geaflow-console-common-util-0.3-SNAPSHOT.jar!/:?]
        at com.antgroup.geaflow.console.common.util.LoaderSwitchUtil.call(LoaderSwitchUtil.java:38) ~[geaflow-console-common-util-0.3-SNAPSHOT.jar!/:?]
        at com.antgroup.geaflow.console.common.util.proxy.ProxyUtil.newInstance(ProxyUtil.java:37) ~[geaflow-console-common-util-0.3-SNAPSHOT.jar!/:?]
        at com.antgroup.geaflow.console.core.service.version.VersionClassLoader.newInstance(VersionClassLoader.java:47) ~[geaflow-console-core-service-0.3-SNAPSHOT.jar!/:?]
        at com.antgroup.geaflow.console.core.service.runtime.K8sRuntime.doStart(K8sRuntime.java:85) ~[geaflow-console-core-service-0.3-SNAPSHOT.jar!/:?]
        ... 7 more
Caused by: io.fabric8.kubernetes.client.KubernetesClientException: An error has occurred.
        at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:64) ~[?:?]
        at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:53) ~[?:?]
        at io.fabric8.kubernetes.client.utils.HttpClientUtils.createHttpClient(HttpClientUtils.java:228) ~[?:?]
        at io.fabric8.kubernetes.client.utils.HttpClientUtils.createHttpClient(HttpClientUtils.java:66) ~[?:?]
        at com.antgroup.geaflow.cluster.k8s.clustermanager.KubernetesClientFactory.create(KubernetesClientFactory.java:70) ~[?:?]
        at com.antgroup.geaflow.cluster.k8s.clustermanager.GeaflowKubeClient.<init>(GeaflowKubeClient.java:56) ~[?:?]
        at com.antgroup.geaflow.cluster.k8s.clustermanager.GeaflowKubeClient.<init>(GeaflowKubeClient.java:52) ~[?:?]
        at com.antgroup.geaflow.cluster.k8s.client.KubernetesJobClient.<init>(KubernetesJobClient.java:58) ~[?:?]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_382]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_382]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_382]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_382]
        at com.antgroup.geaflow.console.common.util.proxy.ProxyUtil.lambda$newInstance$0(ProxyUtil.java:48) ~[geaflow-console-common-util-0.3-SNAPSHOT.jar!/:?]
        at com.antgroup.geaflow.console.common.util.LoaderSwitchUtil.call(LoaderSwitchUtil.java:38) ~[geaflow-console-common-util-0.3-SNAPSHOT.jar!/:?]
        at com.antgroup.geaflow.console.common.util.proxy.ProxyUtil.newInstance(ProxyUtil.java:37) ~[geaflow-console-common-util-0.3-SNAPSHOT.jar!/:?]
        at com.antgroup.geaflow.console.core.service.version.VersionClassLoader.newInstance(VersionClassLoader.java:47) ~[geaflow-console-core-service-0.3-SNAPSHOT.jar!/:?]
        at com.antgroup.geaflow.console.core.service.runtime.K8sRuntime.doStart(K8sRuntime.java:85) ~[geaflow-console-core-service-0.3-SNAPSHOT.jar!/:?]
        ... 7 more
Caused by: java.io.IOException: Invalid DER: object is not integer
        at io.fabric8.kubernetes.client.internal.PKCS1Util$Asn1Object.getInteger(PKCS1Util.java:125) ~[?:?]
        at io.fabric8.kubernetes.client.internal.PKCS1Util.next(PKCS1Util.java:55) ~[?:?]
        at io.fabric8.kubernetes.client.internal.PKCS1Util.decodePKCS1(PKCS1Util.java:46) ~[?:?]
        at io.fabric8.kubernetes.client.internal.CertUtils.handleOtherKeys(CertUtils.java:179) ~[?:?]
        at io.fabric8.kubernetes.client.internal.CertUtils.loadKey(CertUtils.java:139) ~[?:?]
        at io.fabric8.kubernetes.client.internal.CertUtils.createKeyStore(CertUtils.java:115) ~[?:?]
        at io.fabric8.kubernetes.client.internal.CertUtils.createKeyStore(CertUtils.java:251) ~[?:?]
        at io.fabric8.kubernetes.client.internal.SSLUtils.keyManagers(SSLUtils.java:128) ~[?:?]
        at io.fabric8.kubernetes.client.internal.SSLUtils.keyManagers(SSLUtils.java:122) ~[?:?]
        at io.fabric8.kubernetes.client.utils.HttpClientUtils.createHttpClient(HttpClientUtils.java:123) ~[?:?]
        at io.fabric8.kubernetes.client.utils.HttpClientUtils.createHttpClient(HttpClientUtils.java:66) ~[?:?]
        at com.antgroup.geaflow.cluster.k8s.clustermanager.KubernetesClientFactory.create(KubernetesClientFactory.java:70) ~[?:?]
        at com.antgroup.geaflow.cluster.k8s.clustermanager.GeaflowKubeClient.<init>(GeaflowKubeClient.java:56) ~[?:?]
        at com.antgroup.geaflow.cluster.k8s.clustermanager.GeaflowKubeClient.<init>(GeaflowKubeClient.java:52) ~[?:?]
        at com.antgroup.geaflow.cluster.k8s.client.KubernetesJobClient.<init>(KubernetesJobClient.java:58) ~[?:?]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_382]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_382]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_382]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_382]
        at com.antgroup.geaflow.console.common.util.proxy.ProxyUtil.lambda$newInstance$0(ProxyUtil.java:48) ~[geaflow-console-common-util-0.3-SNAPSHOT.jar!/:?]
        at com.antgroup.geaflow.console.common.util.LoaderSwitchUtil.call(LoaderSwitchUtil.java:38) ~[geaflow-console-common-util-0.3-SNAPSHOT.jar!/:?]
        at com.antgroup.geaflow.console.common.util.proxy.ProxyUtil.newInstance(ProxyUtil.java:37) ~[geaflow-console-common-util-0.3-SNAPSHOT.jar!/:?]
        at com.antgroup.geaflow.console.core.service.version.VersionClassLoader.newInstance(VersionClassLoader.java:47) ~[geaflow-console-core-service-0.3-SNAPSHOT.jar!/:?]
        at com.antgroup.geaflow.console.core.service.runtime.K8sRuntime.doStart(K8sRuntime.java:85) ~[geaflow-console-core-service-0.3-SNAPSHOT.jar!/:?]
        ... 7 more
**Expected behavior**

**Additional context**

**Comment by wuyueandrew** [comment]
本地运行是可用的，k8s模式下任务会提交失败

**Comment by pengzhiwei2018** [comment]
@wuyueandrew 感谢反馈，我们看一下这个问题。

**Comment by wuyueandrew** [comment]
https://github.com/fabric8io/kubernetes-client/issues/3535
找到这个，可以参考下

**Comment by qingwen220** [comment]
> [fabric8io/kubernetes-client#3535](https://github.com/fabric8io/kubernetes-client/issues/3535) 找到这个，可以参考下

Maybe you're right. You can try to upgrade the client version to 5.4.2(the current is 5.4.0) or above. You are welcome to contribute the fix to the project and become a contributor.

**Comment by wuyueandrew** [comment]
在问题集群已测试，原因如下：
k8s客户端fabric8默认的加密配置是RSA，出问题的k3s集群使用的是ECDSA，所以会出现认证问题，需要适配多类型的集群。
解决方案：
1.admin控制台增加参数`kubernetes.certs.client.key.algo` value是 `EC`，然后修改`com.antgroup.geaflow.cluster.k8s.clustermanager.KubernetesClientFactory`,增加如上配置的设置可解决。
2.启动geaflow-console的时候增加环境变量`kubernetes.certs.client.key.algo=EC`，可以绕过界面设置，把默认值转换为`EC`，这样无需修改代码。
个人建议2可以作为临时解决，1是更好的解决办法。

**Comment by qingwen220** [comment]
> 

据我了解，k8s高版本的客户端已经支持了ECDSA。可以尝试升级client复杂度并不高。
