### ISSUE TITLE
本地编译docker镜像，GeaFlow Console无法访问

### ISSUE THREAD

**Issue by cooler810** [TuGraph-family/tugraph-analytics#178]
**Describe the bug**
版本 0.2
bash ./build.sh --all
按照本地编译的方式生成了docker镜像，启动镜像后无法访问http://localhost:8888/，查看/opt/geaflow/logs/geaflow-web/stderr.log
`
[root@391b917b038e geaflow-web]# more stderr.log
Error: geaflow-login plugin does not exist
    at Function.getPackageName (/opt/geaflow-web/node_modules/@tugraph/openpiece-server/lib/plugin-manager/PluginManager.js:490:11)
    at Function.resolvePlugin (/opt/geaflow-web/node_modules/@tugraph/openpiece-server/lib/plugin-manager/PluginManager.js:531:30)
    at PluginManager.addStatic (/opt/geaflow-web/node_modules/@tugraph/openpiece-server/lib/plugin-manager/PluginManager.js:246:30)
    at /opt/geaflow-web/node_modules/@tugraph/openpiece-server/lib/plugin-manager/PluginManagerRepository.js:83:27
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/opt/geaflow-web/node_modules/@tugraph/openpiece-server/lib/plugin-manager/PluginManagerRepository.js:22:103)
    at _next (/opt/geaflow-web/node_modules/@tugraph/openpiece-server/lib/plugin-manager/PluginManagerRepository.js:23:194)
`
其他日志没有报错。
docker启动命令为：
`docker run -dit --name geaflow-console -p 8080:8080 -p 8888:8888 -p 3306:3306 -p 6379:6379 -p 8086:8086  -e geaflow.host=192.168.215.188 -e geaflow.web.port=8888 -e geaflow.gateway.port=8080  -e geaflow.web.url=http://192.168.215.188:8888  -e geaflow.web.gateway.url=http://192.168.215.188:8080  -e geaflow.gateway.url=http://192.168.215.188:8080 geaflow-console:0.1`

**Comment by fanzhidongyzby** [comment]
已经修复，请拉取master重新编译
