### ISSUE TITLE
Fix parallelism check exception when run algorithm 

### ISSUE THREAD

**Issue by pengzhiwei2018** [TuGraph-family/tugraph-analytics#49]
**Describe the bug**
When run sssp  with the shard count is 1 for graph, the following exception will throw out:
`com.antgroup.geaflow.common.exception.GeaflowRuntimeException: com.antgroup.geaflow.common.exception.GeaflowRuntimeException: com.antgroup.geaflow.common.exception.GeaflowRuntimeException: java.lang.IllegalArgumentException: Maximum parallelism 1 must not be smaller than parallelism 2
at com.antgroup.geaflow.cluster.task.runner.AbstractTaskRunner.run(AbstractTaskRunner.java:49)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:750)
Caused by: com.antgroup.geaflow.common.exception.GeaflowRuntimeException: com.antgroup.geaflow.common.exception.GeaflowRuntimeException: java.lang.IllegalArgumentException: Maximum parallelism 1 must not be smaller than parallelism 2
at com.antgroup.geaflow.runtime.core.worker.AbstractAlignedWorker.alignedProcess(AbstractAlignedWorker.java:104)
at com.antgroup.geaflow.runtime.core.protocol.AbstractIterationComputeCommand.execute(AbstractIterationComputeCommand.java:51)
at com.antgroup.geaflow.runtime.core.protocol.ExecuteComputeEvent.execute(ExecuteComputeEvent.java:40)
at com.antgroup.geaflow.cluster.task.Task.execute(Task.java:36)
at com.antgroup.geaflow.cluster.task.runner.TaskRunner.process(TaskRunner.java:54)
at com.antgroup.geaflow.cluster.task.runner.TaskRunner.process(TaskRunner.java:24)
at com.antgroup.geaflow.cluster.task.runner.AbstractTaskRunner.run(AbstractTaskRunner.java:43)
... 3 more
Caused by: com.antgroup.geaflow.common.exception.GeaflowRuntimeException: java.lang.IllegalArgumentException: Maximum parallelism 1 must not be smaller than parallelism 2
at com.antgroup.geaflow.processor.impl.window.OneInputProcessor.processElement(OneInputProcessor.java:46)
at com.antgroup.geaflow.processor.impl.window.OneInputProcessor.processElement(OneInputProcessor.java:26)
at com.antgroup.geaflow.processor.impl.AbstractStreamProcessor.process(AbstractStreamProcessor.java:81)
at com.antgroup.geaflow.runtime.core.worker.impl.ComputeWorker.process(ComputeWorker.java:62)
at com.antgroup.geaflow.runtime.core.worker.impl.ComputeWorker.process(ComputeWorker.java:33)`

**Comment by pengzhiwei2018** [comment]
The fix PR has submit: https://github.com/TuGraph-family/tugraph-analytics/pull/50
